module.exports = {
                   username: 'midouramosnap@yahoo.fr',
                   password: 'babi1996',
                   username_selector : '#user_input',
                   password_selector : '#password_input',
                   cta_selector : '#wrapper > div > div > section > div.login > div.login-right > form > input.btn.btn-default',
                   login_url : "https://open.kattis.com/login/email",
                   submit_url : "https://open.kattis.com/submit",
                   user_url : "https://open.kattis.com/users/",
                   btn_selector : '#submit-solution-form > div > div:nth-child(4) > div.col-md-offset-1.col-md-3 > input.btn.btn-default',
                   slct_language : '#s2id_language_select > a',
                   langauge_input : "#s2id_autogen2_search",
                   slct_pblm : '#s2id_problem_select > a',
                   pblm_input : '#s2id_autogen1_search',
                   file_upld : '#sub_files_input',
                   file_dir : "/file/to/path",
                   text_btn_area : "#show_editor_button_sub_code",
                   text_area  : "#sub_code > textarea",
                   span_sub : "#wrapper > div > div:nth-child(2) > section > table > tbody > tr:nth-child(3) > td.status.rejected.middle"
                 }
